# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAcct',
            fields=[
                ('LedgerAcctNum', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('LedgerAcctTxt', models.CharField(max_length=50)),
            ],
        ),
    ]
