# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0002_ledgeracct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailDT', models.DateTimeField(auto_now=True)),
                ('DetailBy', models.IntegerField(choices=[(2, 'admin'), (4, 'crew'), (5, 'cust'), (1, 'ken'), (3, 'mgr')])),
                ('OrigDetailID', models.IntegerField()),
                ('BackOrderDetailID', models.IntegerField()),
                ('QtyOrdered', models.DecimalField(decimal_places=4, max_digits=14)),
                ('QtyBackOrdered', models.DecimalField(decimal_places=4, max_digits=14)),
                ('QtyDelivered', models.DecimalField(decimal_places=4, max_digits=14)),
                ('CPEach', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('ScheduledStartDT', models.DateTimeField()),
                ('ScheduledCompleteDT', models.DateTimeField()),
                ('ActualStartDT', models.DateTimeField()),
                ('ActualCompleteDT', models.DateTimeField()),
                ('FrontNotes', models.TextField(max_length=1000)),
                ('BackNotes', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GoodAndServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=50)),
                ('Class', models.CharField(choices=[('Good', 'Good'), ('Svcs', 'Svcs')], max_length=12)),
                ('LedgerIn', models.IntegerField(choices=[(1000, 'Cash'), (1005, 'ACH'), (1010, 'Accounts Receivable'), (1020, 'Investments'), (1030, 'Inventory'), (1040, 'Equipment'), (1050, 'Vehicles'), (1060, 'Real Estate'), (1070, 'Furniture & Fixtures')], default=0)),
                ('Cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('LedgerOut', models.IntegerField(choices=[(2000, 'Trade Accounts Payable'), (2020, 'Current Loans'), (2030, 'Mortgages'), (3000, 'Paid in Capital'), (3999, 'Retained Earnings'), (4000, 'Sale of Goods'), (4005, 'Shipping Sales'), (4010, 'Sale of Services'), (4020, 'Food Contributions'), (4025, 'Cash Contributions'), (4071, 'Shipping'), (5000, 'Cost of Goods for Sale'), (5003, 'Dry Ice'), (5005, 'Postage & Shipping'), (5010, 'Cost of Services Sold'), (5020, 'Food Distributions'), (5025, 'Spoilage'), (5030, 'Wages'), (5040, 'Administrative Costs'), (5050, 'Office/Warehouse Rent'), (5060, 'Utilities'), (5061, 'Telephone'), (5062, 'Internet Access'), (5065, 'Gas, Oil, & Maintenance'), (5067, 'Vehicle Lease'), (5070, 'Postage'), (5071, 'Shipping'), (5080, 'Interest'), (5085, 'Inventory Shrinkage')], default=0)),
                ('Price', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('PrimarySupplier', models.IntegerField(default=0)),
                ('PrimarySupplierPartNo', models.CharField(max_length=20)),
                ('ImageName', models.CharField(max_length=60)),
                ('QOH', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('SafetyLevel', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('EOQ', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('yadda', 'TYPEA'), ('babba', 'TYPEB')], max_length=10)),
                ('InitialStatus', models.CharField(choices=[('Open', 'Open'), ('Full', 'Full')], max_length=10)),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('Full', 'Full')], max_length=10)),
                ('StatusDT', models.DateTimeField(auto_now=True)),
                ('StatusBy', models.IntegerField(choices=[(2, 'admin'), (4, 'crew'), (5, 'cust'), (1, 'ken'), (3, 'mgr')])),
                ('StatusHistory', models.TextField(max_length=1000)),
                ('AccountingDate', models.DateField()),
                ('EnteredDT', models.DateTimeField(auto_now_add=True)),
                ('EnteredBy', models.IntegerField(choices=[(2, 'admin'), (4, 'crew'), (5, 'cust'), (1, 'ken'), (3, 'mgr')])),
                ('DataEntryCompleteDT', models.DateTimeField()),
                ('DataEntryCompleteBy', models.IntegerField(choices=[(2, 'admin'), (4, 'crew'), (5, 'cust'), (1, 'ken'), (3, 'mgr')])),
                ('CheckedOutToFillDT', models.DateTimeField()),
                ('CheckedOutToFillBy', models.IntegerField(choices=[(2, 'admin'), (4, 'crew'), (5, 'cust'), (1, 'ken'), (3, 'mgr')])),
                ('InOrOut', models.IntegerField(choices=[(1, 'In'), (-1, 'Out')])),
                ('QueuedForPSX12DT', models.DateTimeField()),
                ('SentViaPXS12DT', models.DateTimeField()),
                ('PONumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Relationship',
            field=models.CharField(choices=[('SP', 'Supplier'), ('CU', 'Customer'), ('IN', 'Investor')], default='CU', max_length=2),
        ),
        migrations.AlterField(
            model_name='ledgeracct',
            name='LedgerAcctNum',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='OrdersCustID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hort.Customer'),
        ),
        migrations.AddField(
            model_name='details',
            name='GSID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hort.GoodAndServices'),
        ),
        migrations.AddField(
            model_name='details',
            name='Ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hort.LedgerAcct'),
        ),
        migrations.AddField(
            model_name='details',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hort.Orders'),
        ),
        migrations.AddField(
            model_name='details',
            name='ShipToCustID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hort.Customer'),
        ),
    ]
