# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0004_auto_20160220_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodandservices',
            name='PrimarySupplier',
            field=models.CharField(choices=[('J1234I', 'Investor'), ('W1234W', 'Weedy Wackers Inc.'), ('G1111L', "Guill's Landscaping")], max_length=50),
        ),
    ]
