# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0005_auto_20160221_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Relationship',
            field=models.CharField(choices=[('SUP', 'Supplier'), ('CUS', 'Customer'), ('INV', 'Investor'), ('OWN', 'Owner')], default='CUS', max_length=3),
        ),
    ]
