# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0007_auto_20160221_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodandservices',
            name='ImageName',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
