# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('hort', '0011_auto_20160221_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Url', models.URLField(blank=True, verbose_name='Website')),
                ('Company', models.CharField(blank=True, max_length=50)),
                ('PrimaryRelationship', models.CharField(blank=True, max_length=12)),
                ('PassQuestion', models.CharField(blank=True, max_length=60)),
                ('PassAnswer', models.CharField(blank=True, max_length=60)),
                ('PSX12EnterpriseID', models.CharField(blank=True, max_length=6)),
                ('MailingAddress', models.CharField(blank=True, max_length=60)),
                ('MailingExtraLine', models.CharField(blank=True, max_length=60)),
                ('MailingPostOffice', models.CharField(blank=True, max_length=60)),
                ('MailingZip', models.CharField(blank=True, max_length=60)),
                ('PhoneNumbers', models.CharField(blank=True, max_length=60)),
                ('Notes', models.CharField(blank=True, max_length=1000)),
                ('SourceOfThisRecord', models.CharField(blank=True, max_length=60)),
                ('SourceID', models.CharField(blank=True, max_length=60)),
                ('TakenOnDT', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
