# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodandservices',
            name='LedgerIn',
            field=models.IntegerField(choices=[(1000, 'Cash'), (1005, 'ACH'), (1010, 'Accounts Receivable'), (1020, 'Investments'), (1030, 'Inventory'), (1040, 'Equipment'), (1050, 'Vehicles'), (1060, 'Real Estate'), (1070, 'Furniture & Fixtures'), (2000, 'Trade Accounts Payable'), (2020, 'Current Loans'), (2030, 'Mortgages'), (3000, 'Paid in Capital'), (3999, 'Retained Earnings'), (4000, 'Sale of Goods'), (4005, 'Shipping Sales'), (4010, 'Sale of Services'), (4020, 'Food Contributions'), (4025, 'Cash Contributions'), (4071, 'Shipping'), (5000, 'Cost of Goods for Sale'), (5003, 'Dry Ice'), (5005, 'Postage & Shipping'), (5010, 'Cost of Services Sold'), (5020, 'Food Distributions'), (5025, 'Spoilage'), (5030, 'Wages'), (5040, 'Administrative Costs'), (5050, 'Office/Warehouse Rent'), (5060, 'Utilities'), (5061, 'Telephone'), (5062, 'Internet Access'), (5065, 'Gas, Oil, & Maintenance'), (5067, 'Vehicle Lease'), (5070, 'Postage'), (5071, 'Shipping'), (5080, 'Interest'), (5085, 'Inventory Shrinkage')], default=0),
        ),
        migrations.AlterField(
            model_name='goodandservices',
            name='LedgerOut',
            field=models.IntegerField(choices=[(1000, 'Cash'), (1005, 'ACH'), (1010, 'Accounts Receivable'), (1020, 'Investments'), (1030, 'Inventory'), (1040, 'Equipment'), (1050, 'Vehicles'), (1060, 'Real Estate'), (1070, 'Furniture & Fixtures'), (2000, 'Trade Accounts Payable'), (2020, 'Current Loans'), (2030, 'Mortgages'), (3000, 'Paid in Capital'), (3999, 'Retained Earnings'), (4000, 'Sale of Goods'), (4005, 'Shipping Sales'), (4010, 'Sale of Services'), (4020, 'Food Contributions'), (4025, 'Cash Contributions'), (4071, 'Shipping'), (5000, 'Cost of Goods for Sale'), (5003, 'Dry Ice'), (5005, 'Postage & Shipping'), (5010, 'Cost of Services Sold'), (5020, 'Food Distributions'), (5025, 'Spoilage'), (5030, 'Wages'), (5040, 'Administrative Costs'), (5050, 'Office/Warehouse Rent'), (5060, 'Utilities'), (5061, 'Telephone'), (5062, 'Internet Access'), (5065, 'Gas, Oil, & Maintenance'), (5067, 'Vehicle Lease'), (5070, 'Postage'), (5071, 'Shipping'), (5080, 'Interest'), (5085, 'Inventory Shrinkage')], default=0),
        ),
    ]
