# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0017_auto_20160313_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Relationship',
            field=models.CharField(choices=[('SUP', 'Supplier'), ('CUS', 'Customer'), ('INV', 'Investor'), ('OWN', 'Owner'), ('EMP', 'Employee')], default='CUS', max_length=3),
        ),
        migrations.AlterField(
            model_name='goodandservices',
            name='PrimarySupplier',
            field=models.CharField(choices=[('W1234W', 'Weedy Wackers Inc.'), ('G1111L', "Guill's Landscaping"), ('S1245G', "Smitty's Garden Supply")], max_length=50),
        ),
    ]
