# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0020_auto_20160321_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='InOrOut',
            field=models.IntegerField(blank=True, choices=[(1, 'In [1]'), (-1, 'Out [-1]')]),
        ),
    ]
