# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0023_auto_20160324_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='StatusHistory',
            new_name='OrderNotes',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ActualCompleteDT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ActualStartDT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='BackNotes',
        ),
        migrations.RemoveField(
            model_name='details',
            name='BackOrderDetailID',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DetailBy',
        ),
        migrations.RemoveField(
            model_name='details',
            name='DetailDT',
        ),
        migrations.RemoveField(
            model_name='details',
            name='FrontNotes',
        ),
        migrations.RemoveField(
            model_name='details',
            name='OrigDetailID',
        ),
        migrations.RemoveField(
            model_name='details',
            name='QtyDelivered',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ShipToCustID',
        ),
        migrations.RemoveField(
            model_name='goodandservices',
            name='EOQ',
        ),
        migrations.RemoveField(
            model_name='goodandservices',
            name='ImageName',
        ),
        migrations.RemoveField(
            model_name='goodandservices',
            name='QOH',
        ),
        migrations.RemoveField(
            model_name='goodandservices',
            name='SafetyLevel',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='AccountingDate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='CheckedOutToFillBy',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='CheckedOutToFillDT',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='DataEntryCompleteBy',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='DataEntryCompleteDT',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='InitialStatus',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='QueuedForPSX12DT',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='SentViaPXS12DT',
        ),
        migrations.AddField(
            model_name='customer',
            name='User_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='EnteredBy',
            field=models.IntegerField(choices=[(2, 'admin'), (4, 'crew'), (5, 'cust'), (6, 'guest'), (1, 'ken'), (3, 'mgr')]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='StatusBy',
            field=models.IntegerField(blank=True, choices=[(2, 'admin'), (4, 'crew'), (5, 'cust'), (6, 'guest'), (1, 'ken'), (3, 'mgr')]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='StatusDT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
