# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0025_auto_20160327_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodandservices',
            name='PrimarySupplierPartNo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
