# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0026_auto_20160327_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='AccountingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodandservices',
            name='PrimarySupplier',
            field=models.CharField(choices=[('W1234W', 'Weedy Wackers Inc.'), ('G1111L', "Guill's Landscaping"), ('S1245G', "Smitty's Garden Supply"), ('K9999C', 'Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='StatusDT',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
