# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0027_auto_20160327_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='QtyBackOrdered',
            new_name='QtyInOrOut',
        ),
    ]
