# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0030_auto_20160417_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ExtPrice',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14),
        ),
    ]
