# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0031_details_extprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='CPEach',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='details',
            name='ExtPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='details',
            name='QtyInOrOut',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='QtyOrdered',
            field=models.IntegerField(null=True),
        ),
    ]
