# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0032_auto_20160418_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodandservices',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='goodandservices',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
