# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0033_auto_20160418_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='AcctEntry',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
