# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0035_auto_20160418_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='OrderID',
            field=models.IntegerField(),
        ),
    ]
